//! Pins the TUI word-selection model to the REAL pinned Pi word-selector.
//! The ground-truth table in `tests/fixtures/word_oracle.json` is generated by
//! `tools/reference_fixtures/cases/word_oracle.mts`, which invokes the actual
//! `TuiAltScreen.prototype.getWordSelection`/`getLineSelection`/`visibleWidth`
//! from the pinned `@earendil-works/pi-tui@0.84.4` in the fixed reference
//! checkout — no re-typed algorithm. Every display cell of every sample line
//! is compared, so a regression in either the Rust model or the generated
//! oracle is caught cell by cell.

use minicore_tui::app::ui_actions::word_cell_bounds;
use serde_json::Value;

const FIXTURE: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/tests/fixtures/word_oracle.json"
);

fn load_cases() -> Vec<(String, String, usize, usize, usize, usize)> {
    let raw = std::fs::read_to_string(FIXTURE).expect("word oracle fixture must exist");
    let value: Value = serde_json::from_str(&raw).expect("word oracle fixture must be valid JSON");
    assert_eq!(value["schema"], "minicore-word-oracle-v1");
    assert_eq!(value["pi"], "0.84.4");
    assert_eq!(
        value["rail_commit"],
        "1d0dd1611a4d9546c64fe9f5b5c966253fb88eba"
    );
    assert!(
        value["source"]
            .as_str()
            .is_some_and(|source| source.contains("TuiAltScreen")),
        "fixture must declare the real native source of the oracle"
    );
    let cases = value["cases"].as_array().expect("cases");
    cases
        .iter()
        .map(|case| {
            (
                case["line"].as_str().expect("line").to_owned(),
                case["kind"].as_str().expect("kind").to_owned(),
                case["col"].as_u64().expect("col") as usize,
                case["start"].as_u64().expect("start") as usize,
                case["end"].as_u64().expect("end") as usize,
                case["width"].as_u64().expect("width") as usize,
            )
        })
        .collect()
}

#[test]
fn word_cell_bounds_matches_the_pinned_native_pi_word_selector() {
    let cases = load_cases();
    let word_cases: Vec<_> = cases
        .iter()
        .filter(|(_, kind, ..)| kind == "word")
        .collect();
    assert!(
        word_cases.len() >= 250,
        "word oracle should be a dense cell matrix"
    );
    let mut mismatches = Vec::new();
    for (line, _kind, col, start, end, width) in &word_cases {
        let (got_start, got_end) = word_cell_bounds(line, *col);
        if got_start != *start || got_end != *end {
            mismatches.push(format!(
                "line {line:?} col {col} (width {width}): expected {start}..{end}, got {got_start}..{got_end}"
            ));
            if mismatches.len() >= 10 {
                break;
            }
        }
    }
    assert!(
        mismatches.is_empty(),
        "word model diverges from the pinned native Pi oracle:\n{}",
        mismatches.join("\n")
    );
}

#[test]
fn paragraph_line_selection_is_the_full_native_width() {
    // `getLineSelection` always spans the whole visual line; each cell of
    // every oracle line must agree.
    let cases = load_cases();
    let line_cases: Vec<_> = cases
        .iter()
        .filter(|(_, kind, ..)| kind == "line")
        .collect();
    assert!(!line_cases.is_empty());
    for (line, _kind, _col, start, end, width) in &line_cases {
        assert_eq!(*start, 0, "line selection starts at the rail edge");
        assert_eq!(*end, *width, "line selection covers the full native width");
        let _ = line;
    }
}
