// Fixture emission: provenance + normalized cell grids written under
// tests/fixtures/rail/. One JSON file per case, grouped by area.

import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";
import { parseAnsiRow, encodeRow } from "./ansi.mts";
import { PINNED_PI_VERSION, PINNED_RAIL_COMMIT } from "./ctx.mts";

export const FIXTURE_ROOT = path.resolve(
	path.dirname(fileURLToPath(import.meta.url)),
	"..",
	"..",
	"..",
	"tests",
	"fixtures",
	"rail",
);

export const PROVENANCE = {
	schema: "minicore-rail-cell-v1",
	rail_repo: "zqcli/pi-rail-ui",
	rail_commit: PINNED_RAIL_COMMIT,
	rail_commit_subject: "refactor: rename railfast command to rail-oai-fast",
	rail_ref_dir: "RAIL_REF_DIR (resolved at generation time)",
	pi: PINNED_PI_VERSION,
	theme: "pi dark (initTheme('dark'))",
	node: process.version,
	tz: "UTC",
	generator: "tools/reference_fixtures/generate.mts",
	generated_at: new Date().toISOString(),
	notes:
		"Cells are captured by invoking the fixed Rail/Pi renderer functions (" +
		"RailEditor, native Editor paste, renderExecutionRail, renderSimpleFooter, " +
		"SurfaceRailBlock, collapseHint, railScrollbarGeometry, native Markdown). " +
		"JSON files hold normalized cell grids; terminal transparent background is " +
		"represented by the absence of a bg value.",
};

export function writeProvenance(): void {
	fs.mkdirSync(FIXTURE_ROOT, { recursive: true });
	fs.writeFileSync(
		path.join(FIXTURE_ROOT, "PROVENANCE.json"),
		JSON.stringify(PROVENANCE, null, 2) + "\n",
	);
	fs.writeFileSync(
		path.join(FIXTURE_ROOT, ".gitignore"),
		"# fixtures under this directory are generated by tools/reference_fixtures\n# regenerate with `bash tools/reference_fixtures/bootstrap.sh`\n",
	);
}

export type CapturedRows = {
	rows: string[];
	cursor?: [number, number];
	osczones?: number[];
	term: { cols: number; rows: number };
};

export function captureGrid(caseName: string, term: { cols: number; rows: number }, lines: string[]): unknown {
	const parsed = lines.map((line, index) => {
		const row = parseAnsiRow(line);
		return row;
	});

	let cursor: [number, number] | undefined;
	const osczones: number[] = [];
	const grid: unknown[][] = [];

	for (let index = 0; index < parsed.length; index++) {
		const row = parsed[index]!;
		if (row.cursorCol !== undefined) cursor = [index, row.cursorCol];
		if (row.osczone) osczones.push(index);
		grid.push(encodeRow(row.cells));
	}

	const doc: Record<string, unknown> = {
		schema: PROVENANCE.schema,
		case: caseName,
		term: { cols: term.cols, rows: term.rows },
		source: {
			rail_commit: PROVENANCE.rail_commit,
			pi: PROVENANCE.pi,
			theme: PROVENANCE.theme,
		},
	};
	if (cursor) doc.cursor = cursor;
	if (osczones.length > 0) doc.osczones = osczones;
	doc.rows = grid;
	return doc;
}

export function writeCase(group: string, caseName: string, term: { cols: number; rows: number }, lines: string[], kind: "cells" | "text" = "cells"): string {
	const dir = path.join(FIXTURE_ROOT, group);
	fs.mkdirSync(dir, { recursive: true });
	const file = path.join(dir, `${caseName}.json`);
	if (kind === "text") {
		const doc: Record<string, unknown> = {
			schema: PROVENANCE.schema,
			case: caseName,
			kind: "text",
			term: { cols: term.cols, rows: term.rows },
			source: {
				rail_commit: PROVENANCE.rail_commit,
				pi: PROVENANCE.pi,
				theme: PROVENANCE.theme,
			},
			rows: lines,
		};
		fs.writeFileSync(file, JSON.stringify(doc, null, 1) + "\n");
		return file;
	}
	const doc = captureGrid(caseName, term, lines);
	doc.kind = kind;
	fs.writeFileSync(file, JSON.stringify(doc, null, 1) + "\n");
	return file;
}

/** Cells fixture with a few plain-text annotation lines (state notes, hidden
 * counts, submitted-buffer oracles) kept separate from the pure cell grid. */
export function writeCaseAnnotated(
	group: string,
	caseName: string,
	term: { cols: number; rows: number },
	annotations: string[],
	rows: string[],
): string {
	const doc = captureGrid(caseName, term, rows);
	doc.kind = "cells";
	if (annotations.length > 0) doc.annotations = annotations;
	const dir = path.join(FIXTURE_ROOT, group);
	fs.mkdirSync(dir, { recursive: true });
	const file = path.join(dir, `${caseName}.json`);
	fs.writeFileSync(file, JSON.stringify(doc, null, 1) + "\n");
	return file;
}